sudo: required
services:
  - docker
env:
  DOCKER_COMPOSE_VERSION: 1.18.0
before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
before_script:
  - docker network create test
  - docker rm -f $(docker ps -aq)
  - docker-compose -f docker-compose-dev.yml up --build -d

script:
  - docker-compose -f docker-compose-dev.yml run users python manage.py test
  - docker-compose -f docker-compose-dev.yml run users flake8 project

notifications:
  email:
    recipients:
      - sangnd@vnext.vn
    on_success: never # default: change
    on_failure: always # default: always
  slack: ci-travis:DVmoGFW8BCN3iMzKZxw48wE9


after_script:
  - docker-compose -f docker-compose-dev.yml down